server.port: 8081

spring:
  datasource.url: ${JDBC_DATABASE_URL}
  datasource.username: ${JDBC_DATABASE_USERNAME}
  datasource.password: ${JDBC_DATABASE_PASSWORD}
  #datasource.url: jdbc:postgresql://localhost:6432/hh
  #datasource.username: hh
  #datasource.password: hh

validator:
  address: https://phonevalidation.abstractapi.com/v1
  token: 4cb84ecdd635491799714ba32dcaf2fd

client:
  timeout:
    connect: 30
    read: 60
