server.port: 8081

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:6432/hh
    #username: hh
    #password: hh

validator:
  address: https://phonevalidation.abstractapi.com/v1
  token: 4cb84ecdd635491799714ba32dcaf2fd

client:
  timeout:
    connect: 30
    read: 60

jackson-datetime-format: yyyy-MM-dd'T'HH:mm:ss

key-history-limit: 10

default-page-size: 20
